import Vue from 'vue'
import { Tabbar, TabbarItem, Button, Icon, Grid, GridItem, NavBar, Field, Form, Toast, Dialog, Search, Swipe, SwipeItem, DropdownMenu, DropdownItem, Area, IndexBar, IndexAnchor, Cell, CellGroup, Picker, Image as VanImage, Tag } from 'vant'

Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Button)
Vue.use(Icon)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(NavBar)
Vue.use(Field)
Vue.use(Form)
Vue.use(Toast)
Vue.use(Dialog)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Area)
Vue.use(IndexBar)
Vue.use(IndexAnchor)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(Picker)
Vue.use(VanImage)
Vue.use(Tag)
